version: “4”
services:
  HubServices:
    image: selenium/hub
    container_name: seleniumHub
    ports:
      - “4445:4444”
      - “4442:4442”
      - “4443:4443”

  ChromeService:
    image: selenium/node-chrome-debug
    she_size: “2gb”
    ports:
      - “5900”
      - “7900”
    environments:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=1
    depends_on:
      - HubService

  FirefoxService:
    image: selenium/node-firefox-debug
    ports:
      - “5900”
      - “7900”
    environments:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=1
    depends_on:
      - HubService
